"""first_revision

Revision ID: 2fc09ce61c04
Revises: 
Create Date: 2024-07-23 13:12:38.826186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc09ce61c04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_no',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_number', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('group_lists',
    sa.Column('group_id_fk', sa.Integer(), nullable=False),
    sa.Column('student_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id_fk'], ['group_no.group_id'], ),
    sa.ForeignKeyConstraint(['student_id_fk'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('group_id_fk', 'student_id_fk')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('teacher_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id_fk'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id_fk', sa.Integer(), nullable=False),
    sa.Column('subject_id_fk', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id_fk'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id_fk'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('subjects')
    op.drop_table('group_lists')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('group_no')
    # ### end Alembic commands ###
